#pragma once

#define ID_ROOT_MENU_ITEM_EXIT 500

#define ID_ROOT_MENU_ITEM_AUTHOR 1001
#define ID_ROOT_MENU_ITEM_PROJECT 1002

#define ID_BUTTON_GENERATE_N_SORT 2001
#define ID_BUTTON_SEND_DATA 2002

#define WM_ERROR WM_USER
#define WM_SOCKET_READY WM_USER + 3
#define WM_CONNECTED WM_USER + 4