#pragma once

#define ID_ROOT_MENU_ITEM_EXIT 500

#define ID_ROOT_MENU_ITEM_AUTHOR 1001
#define ID_ROOT_MENU_ITEM_PROJECT 1002

#define ID_BUTTON_CREATE_CONNECTION 2001

#define WM_ERROR WM_USER
#define WM_SOCKET_READY WM_USER + 3
#define WM_CONNECTED WM_USER + 4